[package]
name = "Node"
build = "build.rs"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.14.1"

[build-dependencies]
slint-build = "1.14"

[dev-dependencies]

[profile.dev.package."*"]
opt-level = 3
